name: cheese
adopt-info: cheese
# Temporary manual setting version number 
# https://gitlab.gnome.org/GNOME/cheese/-/merge_requests/60
version: '41.1'
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core20

slots:
  # for GtkApplication registration
  cheese:
    interface: dbus
    bus: session
    name: org.gnome.Cheese

apps:
  cheese:
    extensions: [ gnome-3-38 ]
    command: usr/bin/cheese
    desktop: usr/share/applications/org.gnome.Cheese.desktop
    plugs:
      - audio-playback
      - camera
      - home

parts:
  cheese:
    source: https://gitlab.gnome.org/GNOME/cheese.git
    source-type: git
    source-tag: '41.1'
    parse-info: [usr/share/metainfo/org.gnome.Cheese.appdata.xml]
    override-build: |
      sed -i.bak -e 's|=org.gnome.Cheese$|=${SNAP}/meta/gui/org.gnome.Cheese.svg|g' $SNAPCRAFT_PART_SRC/data/org.gnome.Cheese.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp $SNAPCRAFT_PART_SRC/data/icons/scalable/org.gnome.Cheese.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp data/org.gnome.Cheese.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters:
     - --prefix=/usr
     - -Dgtk_doc=false
     - -Dman=false
    organize:
      snap/cheese/current/usr: usr
    build-packages:
     - gnome-video-effects-dev
     - libcanberra-gtk3-dev
     - libclutter-gst-3.0-dev
     - libgstreamer-plugins-bad1.0-dev
    stage-packages:
    - gnome-video-effects
    - libclutter-gst-3.0-0
